In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("../data/loan_data.csv")
df.head()

,Customer_ID,Gender,Marital_Status,Number_of_Dependents,Education,Loan_Status,Annual_Income,Credit_Score,Loan_Amount,Term,Property_Area,Loan_Approval
0,LP216038,Female,No,2,Graduate,No,4809.0,3329.0,3650.0,180,Rural,Yes
1,LP288956,Female,Yes,1,Graduate,No,3358.0,NaN,6680.0,360,Rural,No
2,LP153364,Female,Yes,1,Graduate,No,9873.0,1649.0,NaN,360,Semiurban,No
3,LP945891,Male,No,0,Graduate,Yes,11665.0,4378.0,8366.0,360,Rural,Yes
4,LP425056,Female,No,1,Graduate,No,5890.0,1523.0,8741.0,180,Urban,Yes

### Task 1: Dataset Understanding and Exploration

In [3]:
def display_rows_cols():
    print(f"Number of rows: {df.shape[0]}")
    print(f"Number of columns: {df.shape[1]}")
    
display_rows_cols()

Number of rows: 10000
Number of columns: 12

In [4]:
df.shape

(10000, 12)

In [5]:
df.head()

,Customer_ID,Gender,Marital_Status,Number_of_Dependents,Education,Loan_Status,Annual_Income,Credit_Score,Loan_Amount,Term,Property_Area,Loan_Approval
0,LP216038,Female,No,2,Graduate,No,4809.0,3329.0,3650.0,180,Rural,Yes
1,LP288956,Female,Yes,1,Graduate,No,3358.0,NaN,6680.0,360,Rural,No
2,LP153364,Female,Yes,1,Graduate,No,9873.0,1649.0,NaN,360,Semiurban,No
3,LP945891,Male,No,0,Graduate,Yes,11665.0,4378.0,8366.0,360,Rural,Yes
4,LP425056,Female,No,1,Graduate,No,5890.0,1523.0,8741.0,180,Urban,Yes

In [6]:
df.tail()

,Customer_ID,Gender,Marital_Status,Number_of_Dependents,Education,Loan_Status,Annual_Income,Credit_Score,Loan_Amount,Term,Property_Area,Loan_Approval
9995,LP693571,Male,Yes,3+,Graduate,Yes,8998.0,2137.0,2487.0,360,Semiurban,Yes
9996,LP193182,Female,No,1,Graduate,Yes,7186.0,NaN,5380.0,360,Rural,Yes
9997,LP668937,Male,No,0,Not Graduate,No,2778.0,678.0,2794.0,180,Rural,Yes
9998,LP447580,Male,No,3+,Graduate,Yes,4746.0,1172.0,NaN,180,Semiurban,No
9999,LP146890,Female,Yes,1,Graduate,No,NaN,1839.0,6084.0,360,Rural,Yes

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Customer_ID           10000 non-null  str
 1   Gender                10000 non-null  str
 2   Marital_Status        10000 non-null  str
 3   Number_of_Dependents  10000 non-null  str
 4   Education             10000 non-null  str
 5   Loan_Status           10000 non-null  str
 6   Annual_Income         9000 non-null   float64
 7   Credit_Score          8979 non-null   float64
 8   Loan_Amount           8987 non-null   float64
 9   Term                  10000 non-null  int64
 10  Property_Area         10000 non-null  str
 11  Loan_Approval         10000 non-null  str
dtypes: float64(3), int64(1), str(8)
memory usage: 937.6 KB

Information of the dataset including number of rows, columns, columns' name, data type, size

In [8]:
df.describe()

       Annual_Income  Credit_Score   Loan_Amount          Term
count    9000.000000   8979.000000   8987.000000  10000.000000
mean     6740.199667   2622.278316   4995.397797    269.334000
std      3019.882729   1381.345574   2860.382446     90.002036
min      1500.000000      0.000000      0.000000    180.000000
25%      4181.000000   1437.000000   2529.500000    180.000000
50%      6669.000000   2627.000000   5021.000000    180.000000
75%      9333.000000   3800.000000   7460.500000    360.000000
max     12000.000000   5000.000000  10000.000000    360.000000

Summary statistics of those columns having float and int data type.

In [9]:
df.dtypes

Customer_ID                 str
Gender                      str
Marital_Status              str
Number_of_Dependents        str
Education                   str
Loan_Status                 str
Annual_Income           float64
Credit_Score            float64
Loan_Amount             float64
Term                      int64
Property_Area               str
Loan_Approval               str
dtype: object

Above information exhibit ***'Annual_Income', 'Credit_Score', 'Loan_Amount', 'Term'*** columns are *string* data type, ***'Annual_Income', 'Credit_Score', 'Loan_Amount'*** are *float* data type, and ***'Term'*** is the *int* data type.

In [10]:
# categorial features
cat_cols = df.select_dtypes(include=['object', 'category']).columns.to_list()
cat_cols

['Customer_ID',
 'Gender',
 'Marital_Status',
 'Number_of_Dependents',
 'Education',
 'Loan_Status',
 'Property_Area',
 'Loan_Approval']

In [11]:
# numerical features
num_cols = df.select_dtypes(include=[float, int]).columns.to_list()
num_cols

['Annual_Income', 'Credit_Score', 'Loan_Amount', 'Term']

### Task 2: Descriptive Statistical Analysis

In [12]:
df.describe()

       Annual_Income  Credit_Score   Loan_Amount          Term
count    9000.000000   8979.000000   8987.000000  10000.000000
mean     6740.199667   2622.278316   4995.397797    269.334000
std      3019.882729   1381.345574   2860.382446     90.002036
min      1500.000000      0.000000      0.000000    180.000000
25%      4181.000000   1437.000000   2529.500000    180.000000
50%      6669.000000   2627.000000   5021.000000    180.000000
75%      9333.000000   3800.000000   7460.500000    360.000000
max     12000.000000   5000.000000  10000.000000    360.000000

In [13]:
def line():
    print("\n" + 100*"=" + "\n")

In [14]:
for col in num_cols:
    print(col)
    print(f"Mean: {df[col].mean()}")
    print(f"Median: {df[col].median()}")
    
    print("Mode:")
    print(df[col].mode())
    print(f"Maximum: {df[col].max()}")
    print(f"Minimum: {df[col].min()}")
    print(f"Range: {df[col].max() - df[col].min()}")

    print(f"Variance: {df[col].var()}")
    print(f"Standard Deviation: {df[col].std()}")
    print("Quartiles")
    print(f"25th percentile: {df[col].quantile(0.25)}")
    print(f"50th percentile: {df[col].quantile(0.50)}")
    print(f"75th percentile: {df[col].quantile(0.75)}")
    
    line()

Annual_Income
Mean: 6740.199666666666
Median: 6669.0
Mode:
0    3016.0
1    5036.0
Name: Annual_Income, dtype: float64
Maximum: 12000.0
Minimum: 1500.0
Range: 10500.0
Variance: 9119691.697766308
Standard Deviation: 3019.8827291413663
Quartiles
25th percentile: 4181.0
50th percentile: 6669.0
75th percentile: 9333.0

====================================================================================================

Credit_Score
Mean: 2622.278316070832
Median: 2627.0
Mode:
0    1303.0
1    1723.0
2    2137.0
3    4266.0
Name: Credit_Score, dtype: float64
Maximum: 5000.0
Minimum: 0.0
Range: 5000.0
Variance: 1908115.5956213118
Standard Deviation: 1381.3455742938881
Quartiles
25th percentile: 1437.0
50th percentile: 2627.0
75th percentile: 3800.0

====================================================================================================

Loan_Amount
Mean: 4995.397796817625
Median: 5021.0
Mode:
0     261.0
1    1861.0
2    1874.0
3    2895.0
4    4979.0
5    8499.0
Name: Loan_Amount, dtype: float64
Maximum: 10000.0
Minimum: 0.0
Range: 10000.0
Variance: 8181787.73880218
Standard Deviation: 2860.3824462477355
Quartiles
25th percentile: 2529.5
50th percentile: 5021.0
75th percentile: 7460.5

====================================================================================================

Term
Mean: 269.334
Median: 180.0
Mode:
0    180
Name: Term, dtype: int64
Maximum: 360
Minimum: 180
Range: 180
Variance: 8100.366480648065
Standard Deviation: 90.00203598057138
Quartiles
25th percentile: 180.0
50th percentile: 180.0
75th percentile: 360.0

====================================================================================================

### Task 3: Exploratory Data Analysis (EDA)

##### 1. Duplicate values analysis

In [15]:
df.duplicated().sum()

np.int64(0)

0 means the dataset does not have duplicate values

##### 2. Missing values analysis

In [16]:
df.isnull().sum()

Customer_ID                0
Gender                     0
Marital_Status             0
Number_of_Dependents       0
Education                  0
Loan_Status                0
Annual_Income           1000
Credit_Score            1021
Loan_Amount             1013
Term                       0
Property_Area              0
Loan_Approval              0
dtype: int64

In [17]:
# columns having missing values
missing_value_cols = df.columns[df.isnull().any()].to_list()
missing_value_cols

['Annual_Income', 'Credit_Score', 'Loan_Amount']

***'Annual_Income', 'Credit_Score', 'Loan_Amount'*** columns have missing values

In [18]:
# finding how much proportion of columns have missing values
for mvc in missing_value_cols:
    print(f"{mvc} column has {round(df[mvc].isnull().mean() * 100, 2)}% missing values.")

Annual_Income column has 10.0% missing values.
Credit_Score column has 10.21% missing values.
Loan_Amount column has 10.13% missing values.

In [19]:
# filling NANs values by respective median value
for col in missing_value_cols:
    median_val = df[col].median()
    # median value
    print(f'{col} median: {median_val}')
    
    # filling NaN by median
    df[col] = df[col].fillna(median_val)

Annual_Income median: 6669.0
Credit_Score median: 2627.0
Loan_Amount median: 5021.0

In [20]:
# after imputation
df.isnull().sum()

Customer_ID             0
Gender                  0
Marital_Status          0
Number_of_Dependents    0
Education               0
Loan_Status             0
Annual_Income           0
Credit_Score            0
Loan_Amount             0
Term                    0
Property_Area           0
Loan_Approval           0
dtype: int64

All missing values are filled by median value.

##### 3. Handling inconsistent data

In [21]:
for col in cat_cols:
    print(col)
    df[col] = df[col].str.strip()
    print(df[col].sort_values().unique())
    
    line()

Customer_ID
<StringArray>
['LP100014', 'LP100194', 'LP100391', 'LP100400', 'LP100422', 'LP100458',
 'LP100481', 'LP101198', 'LP101209', 'LP101261',
 ...
 'LP999295', 'LP999326', 'LP999464', 'LP999487', 'LP999523', 'LP999553',
 'LP999679', 'LP999760', 'LP999769', 'LP999975']
Length: 9940, dtype: str

====================================================================================================

Gender
<StringArray>
['Female', 'Male']
Length: 2, dtype: str

====================================================================================================

Marital_Status
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

====================================================================================================

Number_of_Dependents
<StringArray>
['0', '1', '2', '3+']
Length: 4, dtype: str

====================================================================================================

Education
<StringArray>
['Graduate', 'Not Graduate']
Length: 2, dtype: str

====================================================================================================

Loan_Status
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

====================================================================================================

Property_Area
<StringArray>
['Rural', 'Semiurban', 'Urban']
Length: 3, dtype: str

====================================================================================================

Loan_Approval
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

====================================================================================================

All categorical features have consistent string values except **Number_of_Dependents** column, which has categorical data i.e ['0', '1', '2', '3+'], and needs to be int data type.

In [30]:
# repalce '3+' by 3 and data conversion into int
df["Number_of_Dependents"] = df["Number_of_Dependents"].replace({'3+': 3}).astype(int)

In [32]:
df["Number_of_Dependents"].info()

<class 'pandas.Series'>
RangeIndex: 10000 entries, 0 to 9999
Series name: Number_of_Dependents
Non-Null Count  Dtype
--------------  -----
10000 non-null  int64
dtypes: int64(1)
memory usage: 78.3 KB

In [33]:
df["Number_of_Dependents"].value_counts()

Number_of_Dependents
2    2541
1    2531
0    2478
3    2450
Name: count, dtype: int64

##### 4. Outlier detection using Skewness and Kurtosis

In [28]:
print(f"Skewness: \n{df[num_cols].skew()}")
line()
print(f"Kurtosis: \n{df[num_cols].kurt()}")

Skewness:
Annual_Income    0.033039
Credit_Score    -0.023183
Loan_Amount     -0.001877
Term             0.014803
dtype: float64

====================================================================================================

Kurtosis:
Annual_Income   -0.993376
Credit_Score    -0.943726
Loan_Amount     -0.966989
Term            -2.000181
dtype: float64

Note: 

**Skewness** measures the asymmetry of a distribution.

Skewnesss value between -0.5 and 0.5 indicates that the data is fairly symmetrical so, the values of above numerical features are close to 0, which means values are distributed evenly around the center.

**Kurtosis** measures whether the data is heavy-tailed (lots of outliers) or light-tailed (few outliers) compared to a normal distribution. A standard normal distribution has an excess kurtosis of 0. Negative kurtosis indicates a "Platykurtic" distribution—meaning it is flatter and has thinner tails than a normal bell curve.

Here, the data does not have extreme outliers, which forms a wide, flat plateau rather than a sharp peak.


Note: *The given dataset has perfectly zero skewness and negative kurtosis because the data is artificially generated (synthetic). Real-world financial data is almost always highly right-skewed (most people have average incomes, a few have massive incomes).*

Using a standard IQR calcualtion to check whether the dataset has outliers or not.

In [37]:
# checking outlier in Loan_Amount column
Q1 = df["Loan_Amount"].quantile(0.25)
Q3 = df["Loan_Amount"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)


outliers = df[(df["Loan_Amount"] < lower_bound) | (df["Loan_Amount"] > upper_bound)]

print(f"Number of sever outliers in 'Loan_Amount': {len(outliers)}")

Number of sever outliers in 'Loan_Amount': 0

As data is synthetic, which has 0 outliers in **'Loan_Amount'** column.

In [38]:
# customer IDs are unique identifiers, which has no role for predicition so dropping it
df.drop(columns=["Customer_ID"], inplace=True)

In [39]:
df.columns

Index(['Gender', 'Marital_Status', 'Number_of_Dependents', 'Education',
       'Loan_Status', 'Annual_Income', 'Credit_Score', 'Loan_Amount', 'Term',
       'Property_Area', 'Loan_Approval'],
      dtype='str')

In [41]:
df.groupby("Education")["Loan_Amount"].mean().round(2)

Education
Graduate        4997.97
Not Graduate    4998.01
Name: Loan_Amount, dtype: float64

Average loan amount received by different education levels.

In [43]:
df.sample(8)

,Gender,Marital_Status,Number_of_Dependents,Education,Loan_Status,Annual_Income,Credit_Score,Loan_Amount,Term,Property_Area,Loan_Approval
2447,Male,No,1,Graduate,Yes,6669.0,4164.0,6212.0,360,Rural,Yes
9811,Male,Yes,3,Graduate,Yes,9155.0,1264.0,3007.0,360,Semiurban,No
202,Male,Yes,1,Not Graduate,Yes,6669.0,4473.0,9686.0,180,Urban,Yes
9360,Male,Yes,3,Graduate,Yes,4908.0,2974.0,6222.0,180,Rural,Yes
3848,Female,No,0,Graduate,Yes,3470.0,655.0,5021.0,360,Rural,No
1454,Male,Yes,1,Not Graduate,No,1654.0,3333.0,8477.0,360,Urban,No
7733,Male,No,1,Not Graduate,Yes,5245.0,4170.0,3950.0,180,Semiurban,Yes
5825,Male,Yes,1,Not Graduate,No,6669.0,2871.0,2969.0,180,Rural,Yes

In [48]:
df.loc[(df["Annual_Income"] > 5000) & (df["Loan_Approval"] == "Yes")]

,Gender,Marital_Status,Number_of_Dependents,Education,Loan_Status,Annual_Income,Credit_Score,Loan_Amount,Term,Property_Area,Loan_Approval
3,Male,No,0,Graduate,Yes,11665.0,4378.0,8366.0,360,Rural,Yes
4,Female,No,1,Graduate,No,5890.0,1523.0,8741.0,180,Urban,Yes
9,Male,No,2,Not Graduate,Yes,6810.0,1887.0,1176.0,180,Semiurban,Yes
10,Male,Yes,1,Graduate,No,7912.0,1531.0,9212.0,360,Semiurban,Yes
17,Male,No,3,Graduate,No,10508.0,2627.0,8169.0,360,Urban,Yes
...,...,...,...,...,...,...,...,...,...,...,...
9988,Male,Yes,0,Not Graduate,Yes,6669.0,4994.0,215.0,180,Urban,Yes
9993,Male,Yes,0,Not Graduate,No,10246.0,336.0,6525.0,360,Semiurban,Yes
9995,Male,Yes,3,Graduate,Yes,8998.0,2137.0,2487.0,360,Semiurban,Yes
9996,Female,No,1,Graduate,Yes,7186.0,2627.0,5380.0,360,Rural,Yes
9999,Female,Yes,1,Graduate,No,6669.0,1839.0,6084.0,360,Rural,Yes

Above rows are those data whose has annual income > 5000 and loan approval is acceptable.

In [50]:
num_approval = df.loc[(df["Annual_Income"] > 5000) & (df["Loan_Approval"] == "Yes")]
print(f"Number of customers whose annual income > 5000 and loan is approved: {len(num_approval)}")

Number of customers whose annual income > 5000 and loan is approved: 3517