In [ ]:
import pandas as pd

In [24]:
df = pd.read_csv("../data/loan_data.csv")
df.head()

,Customer_ID,Gender,Marital_Status,Number_of_Dependents,Education,Loan_Status,Annual_Income,Credit_Score,Loan_Amount,Term,Property_Area,Loan_Approval
0,LP216038,Female,No,2,Graduate,No,4809.0,3329.0,3650.0,180,Rural,Yes
1,LP288956,Female,Yes,1,Graduate,No,3358.0,NaN,6680.0,360,Rural,No
2,LP153364,Female,Yes,1,Graduate,No,9873.0,1649.0,NaN,360,Semiurban,No
3,LP945891,Male,No,0,Graduate,Yes,11665.0,4378.0,8366.0,360,Rural,Yes
4,LP425056,Female,No,1,Graduate,No,5890.0,1523.0,8741.0,180,Urban,Yes

### Task 1: Dataset Understanding and Exploration

In [35]:
def display_rows_cols():
    print(f"Number of rows: {df.shape[0]}")
    print(f"Number of columns: {df.shape[1]}")
    
display_rows_cols()

Number of rows: 10000
Number of columns: 12

In [25]:
df.shape

(10000, 12)

In [28]:
df.head()

,Customer_ID,Gender,Marital_Status,Number_of_Dependents,Education,Loan_Status,Annual_Income,Credit_Score,Loan_Amount,Term,Property_Area,Loan_Approval
0,LP216038,Female,No,2,Graduate,No,4809.0,3329.0,3650.0,180,Rural,Yes
1,LP288956,Female,Yes,1,Graduate,No,3358.0,NaN,6680.0,360,Rural,No
2,LP153364,Female,Yes,1,Graduate,No,9873.0,1649.0,NaN,360,Semiurban,No
3,LP945891,Male,No,0,Graduate,Yes,11665.0,4378.0,8366.0,360,Rural,Yes
4,LP425056,Female,No,1,Graduate,No,5890.0,1523.0,8741.0,180,Urban,Yes

In [29]:
df.tail()

,Customer_ID,Gender,Marital_Status,Number_of_Dependents,Education,Loan_Status,Annual_Income,Credit_Score,Loan_Amount,Term,Property_Area,Loan_Approval
9995,LP693571,Male,Yes,3+,Graduate,Yes,8998.0,2137.0,2487.0,360,Semiurban,Yes
9996,LP193182,Female,No,1,Graduate,Yes,7186.0,NaN,5380.0,360,Rural,Yes
9997,LP668937,Male,No,0,Not Graduate,No,2778.0,678.0,2794.0,180,Rural,Yes
9998,LP447580,Male,No,3+,Graduate,Yes,4746.0,1172.0,NaN,180,Semiurban,No
9999,LP146890,Female,Yes,1,Graduate,No,NaN,1839.0,6084.0,360,Rural,Yes

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Customer_ID           10000 non-null  str
 1   Gender                10000 non-null  str
 2   Marital_Status        10000 non-null  str
 3   Number_of_Dependents  10000 non-null  str
 4   Education             10000 non-null  str
 5   Loan_Status           10000 non-null  str
 6   Annual_Income         9000 non-null   float64
 7   Credit_Score          8979 non-null   float64
 8   Loan_Amount           8987 non-null   float64
 9   Term                  10000 non-null  int64
 10  Property_Area         10000 non-null  str
 11  Loan_Approval         10000 non-null  str
dtypes: float64(3), int64(1), str(8)
memory usage: 937.6 KB

Information of the dataset including number of rows, columns, columns' name, data type, size

In [37]:
df.describe()

       Annual_Income  Credit_Score   Loan_Amount          Term
count    9000.000000   8979.000000   8987.000000  10000.000000
mean     6740.199667   2622.278316   4995.397797    269.334000
std      3019.882729   1381.345574   2860.382446     90.002036
min      1500.000000      0.000000      0.000000    180.000000
25%      4181.000000   1437.000000   2529.500000    180.000000
50%      6669.000000   2627.000000   5021.000000    180.000000
75%      9333.000000   3800.000000   7460.500000    360.000000
max     12000.000000   5000.000000  10000.000000    360.000000

Summary statistics of those columns having float and int data type.

In [38]:
df.dtypes

Customer_ID                 str
Gender                      str
Marital_Status              str
Number_of_Dependents        str
Education                   str
Loan_Status                 str
Annual_Income           float64
Credit_Score            float64
Loan_Amount             float64
Term                      int64
Property_Area               str
Loan_Approval               str
dtype: object

Above information exhibit ***'Annual_Income', 'Credit_Score', 'Loan_Amount', 'Term'*** columns are *string* data type, ***'Annual_Income', 'Credit_Score', 'Loan_Amount'*** are *float* data type, and ***'Term'*** is the *int* data type.

In [44]:
# categorial features
cat_cols = df.select_dtypes("str").columns.to_list()
cat_cols

['Customer_ID',
 'Gender',
 'Marital_Status',
 'Number_of_Dependents',
 'Education',
 'Loan_Status',
 'Property_Area',
 'Loan_Approval']

In [45]:
# numerical features
num_cols = df.select_dtypes(include=[float, int]).columns.to_list()
num_cols

['Annual_Income', 'Credit_Score', 'Loan_Amount', 'Term']

### Task 2: Descriptive Statistical Analysis

In [58]:
df.describe()

       Annual_Income  Credit_Score   Loan_Amount          Term
count    9000.000000   8979.000000   8987.000000  10000.000000
mean     6740.199667   2622.278316   4995.397797    269.334000
std      3019.882729   1381.345574   2860.382446     90.002036
min      1500.000000      0.000000      0.000000    180.000000
25%      4181.000000   1437.000000   2529.500000    180.000000
50%      6669.000000   2627.000000   5021.000000    180.000000
75%      9333.000000   3800.000000   7460.500000    360.000000
max     12000.000000   5000.000000  10000.000000    360.000000

In [81]:
for col in num_cols:
    print(col)
    print(f"Mean: {df[col].mean()}")
    print(f"Median: {df[col].median()}")
    
    print("Mode:")
    print(df[col].mode())
    print(f"Maximum: {df[col].max()}")
    print(f"Minimum: {df[col].min()}")
    print(f"Range: {df[col].max() - df[col].min()}")

    print(f"Variance: {df[col].var()}")
    print(f"Standard Deviation: {df[col].std()}")
    print("Quartiles")
    print(f"25th percentile: {df[col].quantile(0.25)}")
    print(f"50th percentile: {df[col].quantile(0.50)}")
    print(f"75th percentile: {df[col].quantile(0.75)}")
    
    print("\n" + 100*"=" + "\n")

Annual_Income
Mean: 6740.199666666666
Median: 6669.0
Mode:
0    3016.0
1    5036.0
Name: Annual_Income, dtype: float64
Maximum: 12000.0
Minimum: 1500.0
Range: 10500.0
Variance: 9119691.697766308
Standard Deviation: 3019.8827291413663
Quartiles
25th percentile: 4181.0
50th percentile: 6669.0
75th percentile: 9333.0

====================================================================================================

Credit_Score
Mean: 2622.278316070832
Median: 2627.0
Mode:
0    1303.0
1    1723.0
2    2137.0
3    4266.0
Name: Credit_Score, dtype: float64
Maximum: 5000.0
Minimum: 0.0
Range: 5000.0
Variance: 1908115.5956213118
Standard Deviation: 1381.3455742938881
Quartiles
25th percentile: 1437.0
50th percentile: 2627.0
75th percentile: 3800.0

====================================================================================================

Loan_Amount
Mean: 4995.397796817625
Median: 5021.0
Mode:
0     261.0
1    1861.0
2    1874.0
3    2895.0
4    4979.0
5    8499.0
Name: Loan_Amount, dtype: float64
Maximum: 10000.0
Minimum: 0.0
Range: 10000.0
Variance: 8181787.73880218
Standard Deviation: 2860.3824462477355
Quartiles
25th percentile: 2529.5
50th percentile: 5021.0
75th percentile: 7460.5

====================================================================================================

Term
Mean: 269.334
Median: 180.0
Mode:
0    180
Name: Term, dtype: int64
Maximum: 360
Minimum: 180
Range: 180
Variance: 8100.366480648065
Standard Deviation: 90.00203598057138
Quartiles
25th percentile: 180.0
50th percentile: 180.0
75th percentile: 360.0

====================================================================================================